.catalog:
  name: "Container-Monitor-Agent"
  version: "0.0.1"
  description: "Container Monitor Agent"
  uuid: container-monitor-agent-1
  minimum_rancher_version: v1.4.3
  questions:
  - variable: "PROMETHEUS_GATEWAY"
    label: "Prometheus Gateway Address"
    description: "Prometheus push gateway address, for example http://10.255.18.40:8080"
    required: true
    type: "string"
  - variable: "DEBUG"
    label: "debug flag"
    description: "use for print debug log"
    required: false
    type: "boolean"
  - variable: "CONTAINER_STATUS_INTERVAL"
    label: "Container status interval"
    description: "the time interval to get the container status"
    required: false
    type: "int"
  - variable: "CONTAINER_METRIC_INTERVAL"
    label: "Container metric interval"
    description: "the time interval to get the container metric"
    required: false
    type: "int"

container-monitor-agent: